/*
 * RegisterConverter.cpp
 *
 *  Created on: 15.07.2010
 *      Author: fkrauthan
 */

#include "RegisterConverter.h"


SERIALIZATION_REGISTER_START(DEFAULT_SERIALIZER)
	SERIALIZATION_STRING()


	SERIALIZATION_GENERIC(int)
	SERIALIZATION_GENERIC(long)
	SERIALIZATION_GENERIC(short)
	SERIALIZATION_GENERIC(char)
	SERIALIZATION_GENERIC(float)
	SERIALIZATION_GENERIC(double)
	SERIALIZATION_GENERIC(bool)
	SERIALIZATION_GENERIC(unsigned int)
	SERIALIZATION_GENERIC(unsigned long)
SERIALIZATION_REGISTER_END(DEFAULT_SERIALIZER)
